version: '3.8'

services:
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: server
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/mydatabase
      JWT_SECRET: e1ea05f7f9b04bd23012e1dc0224c25d40c8cfc6d328e7b16644dac62482e6fb
      HASH_SALT: 10
      TOKEN_EXPIRE_TIME: 30s
    ports:
      - "3000:3000"
    depends_on:
      - database
